import 'package:hive/hive.dart';
part 'book_entities.g.dart'; //This file is automatically generated by the Hive code generator and contains serialization and deserialization logic for the BookEntities class

@HiveType(
    typeId:
        0) //This annotation marks the class BookEntities as a Hive type with a specific typeId. This typeId is used by Hive to uniquely identify the object type in the database.
class BookEntities {
  @HiveField(
      0) //These annotations mark the fields of the BookEntities class that should be serialized and stored in the Hive database. The index parameter specifies the index of the field in the serialization order.
  final String bookId;
  @HiveField(1)
  final String? image;
  @HiveField(2)
  final String title;
  @HiveField(3)
  final String? authourName;
  @HiveField(4)
  final num? price;
  @HiveField(5)
  final num? rating;

  BookEntities(
      {required this.bookId,
      required this.image,
      required this.title,
      required this.authourName,
      required this.price,
      required this.rating});
}
